
on: [push]

jobs:
  Run-minecraft:
    name: Run minecraft
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      mcserver:
        image: itzg/minecraft-server
        ports:
          - 25565:25565
        options: --name minecraftserver

    steps:    
      - name: Get Minecraft container health
        run: /usr/bin/docker container inspect -f "{{.State.Health.Status}}" minecraftserver

      - name: Display Minecraft container logs
        run: /usr/bin/docker logs minecraftserver

